### ISSUE TITLE
à faire un jour

### ISSUE THREAD

**Issue by avouacr** [ensae-reproductibilite/website#18]
- Mamba
- Tests unitaires
- Monitoring
    - Logging
- Versioning avancé 
    - Data version control
    - MLOps
- Optimisation de performance
    - Sin of early optimisation
    - Profiling
    - Ressources
        - R : Advanced R, R inferno
        - Python : High Performance Python
- Bonnes pratiques Dockerfile
- Enjeux de sécurité

**Comment by linogaliana** [comment]
> Mamba

Plus nécessaire, il me semble que ça a été intégré de base dans le solver de conda

> Tests unitaires

Présenté de manière optionnelle dans l'application
